#!/usr/bin/bash
# Author: Geoffery Powell <powellgeoffery@gmail.com>
# Purpose: Remove files matching the provided patterns from provided directory
# Syntax: dirclean [--test] DIRECTORY PATTERN
# Example: ./dirclean --test temp "*.bak" "*.back" "*~"

filesToDelete=()
fileCount=0
cwd=$(pwd)

#### Fuctions
rmFiles () { 
    #echo $fileCount
    if [ $fileCount -le 0 ]; then
        echo "no files deleted"
    fi
    for file in ${filesToDelete[@]}
    do
        echo "Deleting file: $cwd/$file"
        if [ $1 == false ]; then
                rm $file
        fi
    done
}

matchPattern () { #$1=Dir $2+=Pattern
    shopt -s dotglob #Shows hidden or "." files
    # cwd=$(pwd)
    matchFound=false
    #echo Current Working Directory: $(pwd)
    #echo "Pattern: $3"
    for file in "$(pwd)"/*
    do
        fileName=$(basename $file)
        # echo "Filename: $fileName"
        if [[ $fileName = $3 ]]; then
            # echo "$fileName matched pattern"
            for item in "{$filesToDelete[@]}"
            do
                if [ "$fileName" == "$item" ]; then
                    matchFound=true
                    # echo "Match was already in array."
                fi
            done
            if [ $matchFound == false ]; then
                filesToDelete[fileCount]=$fileName
                ((fileCount=fileCount+1))
                # echo "$fileName added to list"
            fi
        fi
    done
}


#### MAIN
if [ $# -ge 2 ]; then
    if [[ $1 == "--test"* ]]; then
        # echo "Test: True"
        TEST=true
        DIRECTORY=$2
        argCount=3
    else
        # echo "Test: False"
        TEST=false
        DIRECTORY=$1
        argCount=2
    fi

    FULLPATH=$cwd"/"$DIRECTORY
    # echo Directory: $DIRECTORY
    if [ -d "$DIRECTORY" ]
    then
        cd ./$DIRECTORY
        cwd=$(pwd)

        # echo "Searching $FULLPATH"
        # Take in patterns
        for PATTERN in "${@:argCount}"; do
            dir=$(readlink -f  $DIRECTORY)
            # echo "Pattern: $PATTERN"
            # Check for pattern matches
            matchPattern $DIRECTORY $TEST "$PATTERN"

            # Remove matching files
            rmFiles $TEST

            # Successful competion:
            exit 0
        done
    else
        echo "DIRECTORY argument is not a valid directory: $FULLPATH"
        exit 1
    fi
else
    # Unsuccessful too few args
    # echo "Not enough args were provided."
    echo "Useage: dirclean [--test] DIRECTORY PATTERN"
    exit 1
fi

# EOF