#!/usr/bin/bash
# Author: Geoffery Powell <powellgeoffery@gmail.com>
# Purpose: Print matching info from provided directories
# Syntax: dirclean [--test] DIRECTORY PATTERN
# Example: ./dirclean --test temp "*.bak" "*.back" "*~"

filesToDelete=()

#### Fuctions
rmFiles () { 
    for file in "{$filesToDelete[@]}"
    do
        echo "Deleting file: $file"
        if [ $1 == false ]; then
                rm $file
        fi
    done
}

printDir () { #$1=Dir $2+=Pattern
    shopt -s dotglob #Shows hidden or "." files
    cwd=$(pwd)
    matchFound=false
    #echo Current Working Directory: $(pwd)
    #echo "Pattern: $3"
    for file in "$(pwd)"/*
    do
        fileName=$(basename $file)
        echo "Filename: $fileName"
        if [[ $fileName = $3 ]]; then
            echo "$fileName matched pattern"
            for item in "{$filesToDelete[@]}"
            do
                if [ "$fileName" == "$item" ]; then
                    matchFound=true
                    echo "Match was already in array."
                fi
            done
            if [ matchFound == false ]; then
                filesToDelete+=$fileName
                echo "$fileName added to list"
            fi
        fi
        #length=${#fileName}
        #file=${file%length}
        #file=$file \"$fileName\"
        #result=$(grep $2 $file)
        #if [ ! -z "$result" ];
        #then
        #    echo $result
        #fi
        #grep "$PATTERN" $file
        #echo $file
    done
}


#### MAIN
cwd=$(pwd)
# echo Current Working Directory: $(pwd)
if [ $# -ge 2 ]; then
    if [[ $1 == "--test"* ]]; then
        echo "Test: True"
        TEST=true
        DIRECTORY=$2
        argCount=3
    else
        echo "Test: False"
        TEST=false
        DIRECTORY=$1
        argCount=2
    fi

    FULLPATH=$cwd"/"$DIRECTORY
    echo Directory: $DIRECTORY

    if [ -d "$DIRECTORY" ]
    then
        cd ./$DIRECTORY
        echo "Searching $FULLPATH"
        echo ""
        # Take in patterns
        for PATTERN in "${@:argCount}"; do
            dir=$(readlink -f  $DIRECTORY)
            echo "Pattern: $PATTERN"
            printDir $DIRECTORY $TEST "$PATTERN"
            echo ""
        done
    else
        echo "$FULLPATH was not found"
    fi

    echo "Thing to delete:"
    for i in "${filesToDelete[@]}"
    do
        echo $i
    done
    # Successful competion:
    exit 0
else
    # Unsuccessful too few args
    echo "Not enough args were provided."
    echo "Useage: dirclean [--test] DIRECTORY PATTERN"
    exit 1
fi

# EOF