#!/usr/bin/bash
# Author: Geoffery Powell <powellgeoffery@gmail.com>
# Purpose: Print matching info from provided directories
# Syntax: dirclean [--test] DIRECTORY PATTERN
# Example: ./dirclean --test temp "*.bak" "*.back" "*~"

#### Fuctions

printDir () { #$1=Dir $2=Test $3+=Pattern
    shopt -s dotglob #Shows hidden or "." files
    cwd=$(pwd)
    #echo Current Working Directory: $(pwd)
    #echo "Pattern: $3"
    for file in "$(pwd)"/*
    do
        fileName=$(basename $file)
        #echo File Name: $fileName
        if [[ "$fileName" =~ ["$3"] ]]; then
            echo "Deleting file: $file"
            if [ $2 == false ]; then
                rm $file
            fi
        fi
        #length=${#fileName}
        #file=${file%length}
        #file=$file \"$fileName\"
        #result=$(grep $2 $file)
        #if [ ! -z "$result" ];
        #then
        #    echo $result
        #fi
        #grep "$PATTERN" $file
        #echo $file
    done
}


#### MAIN
cwd=$(pwd)
# echo Current Working Directory: $(pwd)
if [ $# -ge 2 ]; then
    if [[ $1 == "--test"* ]]; then
        echo "Test: True"
        TEST=true
        DIRECTORY=$2
        argCount=3
    else
        echo "Test: False"
        TEST=false
        DIRECTORY=$1
        argCount=2
    fi

    FULLPATH=$cwd"/"$DIRECTORY
    echo Directory: $DIRECTORY

    if [ -d "$DIRECTORY" ]
    then
        cd ./$DIRECTORY
        echo "Searching $FULLPATH"
        echo ""
        # Take in patterns
        for PATTERN in "${@:argCount}"; do
            dir=$(readlink -f  $DIRECTORY)
            echo "Pattern: $PATTERN"
            printDir $DIRECTORY $TEST "$PATTERN"
            echo ""
        done
    else
        echo "$FULLPATH was not found"
    fi


    # Successful competion:
    exit 0
else
    # Unsuccessful too few args
    echo "Not enough args were provided."
    echo "Useage: dirclean [--test] DIRECTORY PATTERN"
    exit 1
fi

# EOF