#!/bin/bash 

#syntax: findtext [--program=PROGRAM] PATTERN DIRECTORY

#### Fuctions

function printDir {
    shopt -s dotglob #Shows hidden or "." files
    for file in "$1"/*
    do
        echo $(basename $file)
    done
}


#### MAIN

#echo "Positional Parameters"
PROGRAM=$1
PATTERN=$2

#echo $PROGRAM
#echo $PATTERN

#Take in directories
for dir in "${@:3}"; do
    if [ -d "$dir" ]
    then
        printDir $dir
    else
        echo "$dir was not found"
    fi
done


# Successful competion:
exit 0

# EOF