#!/bin/bash 

#syntax: findtext [--program=PROGRAM] PATTERN DIRECTORY

function printDir {
    for f in "$1"/*
    do
        echo $(basename $f)
    done
}


#### MAIN

echo "Positional Parameters"
PROGRAM=$1
PATTERN=$2


DIRECTORY=$3

echo $PROGRAM
echo $PATTERN
echo $DIRECTORY

printDir $DIRECTORY